openapi: "3.0.3"
info:
  title: local-gists
  description: Local clone of github gists
  version: "1.0.0"
servers:
  - url: http://localhost:5000
    description: Dev

components:
  schemas:
    Dates:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    File:
      type: object
      allOf:
        - type: object
          properties:
            gistId:
              type: integer
              readOnly: true
            filename:
              type: string
            content:
              type: string
        - $ref: "#/components/schemas/Dates"

    FileSubmission:
      type: object
      required:
        - filename
      properties:
        filename:
          type: string
          minLength: 1
        content:
          type: string

    FileUpdate:
      type: object
      minProperties: 1
      properties:
        filename:
          type: string
          minLength: 1
        content:
          type: string

    Comment:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: integer
              readOnly: true
            gistId:
              type: integer
              readOnly: true
            content:
              type: string
        - $ref: "#/components/schemas/Dates"

    CommentSubmission:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 1

    Gist:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: integer
              readOnly: true
            title:
              type: string
            description:
              type: string
            slug:
              type: string
              readOnly: true
            files:
              type: array
              minItems: 1
              items:
                $ref: "#/components/schemas/File"
            comments:
              type: array
              items:
                $ref: "#/components/schemas/Comment"
        - $ref: "#/components/schemas/Dates"

    GistInfo:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              readOnly: true
            title:
              type: string
            slug:
              type: string
              readOnly: true
            files:
              type: array
              minItems: 1
              maxItems: 1
              items:
                $ref: "#/components/schemas/File"
            _count:
              type: object
              properties:
                files:
                  type: integer
                comments:
                  type: integer
        - $ref: "#/components/schemas/Dates"

    GistSubmission:
      type: object
      required:
        - title
        - files
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
        files:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/FileSubmission"

    GistUpdate:
      type: object
      minProperties: 1
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              message:
                type: string

paths:
  /gists:
    get:
      tags:
        - Gists
      summary: "Get all gists"
      responses:
        200:
          description: "Returns list of gists"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GistInfo"

    post:
      tags:
        - Gists
      summary: Create a new gist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GistSubmission"
      responses:
        201:
          description: "Returns new gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        409:
          description: "A Gist with same title already exists"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /gists/{id}:
    get:
      tags:
        - Gists
      summary: Get a specific gist data by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "Returns full gist data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      tags:
        - Gists
      summary: Update basic info for a gist
      description: "Only title and description can be updated.\nFiles and comments have their own endpoints"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GistUpdate"
      responses:
        200:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - Gists
      summary: Delete a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: "No content"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /gists/{id}/files:
    post:
      tags:
        - Files
      summary: Add files to a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: "#/components/schemas/FileSubmission"
      responses:
        201:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - Files
      summary: Update files for a gist
      description: "🟨 Replaces (Overwrites) all files for a gist"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: "#/components/schemas/FileSubmission"

      responses:
        200:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /gists/{id}/files/{filename}:
    patch:
      tags:
        - Files
      summary: Update a file in a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: filename
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileUpdate"

      responses:
        200:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "File not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: "A File with same name already exists"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - Files
      summary: Delete a file in a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: "No content"
        404:
          description: "File not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /gists/{id}/comments:
    post:
      tags:
        - Comments
      summary: Add comment to a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentSubmission"

      responses:
        201:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: "Gist not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /gists/{id}/comments/{commentId}:
    put:
      tags:
        - Comments
      summary: Update a comment in a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentSubmission"

      responses:
        200:
          description: "Returns updated gist full data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Gist"

    delete:
      tags:
        - Comments
      summary: Delete comment from a gist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: "No content"

# TODO: Document error responses
